[build]
  publish = "public"
  command = "hugo --gc"
  
[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_BASEURL = "/"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"